# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reflowmonitor.ui'
#
# Created: Sat Aug 29 12:22:39 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,comm):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(810, 666)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(810, 666))
        MainWindow.setMaximumSize(QtCore.QSize(810, 666))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 797, 641))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 12, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.statusframe = QtGui.QFrame(self.layoutWidget)
        self.statusframe.setFrameShape(QtGui.QFrame.WinPanel)
        self.statusframe.setObjectName("statusframe")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.statusframe)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblovenstatus = QtGui.QLabel(self.statusframe)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblovenstatus.setFont(font)
        self.lblovenstatus.setObjectName("lblovenstatus")
        self.verticalLayout_10.addWidget(self.lblovenstatus)
        self.lineovenstatus = QtGui.QLineEdit(self.statusframe)
        self.lineovenstatus.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineovenstatus.setPalette(palette)
        comm.newState.connect(self.lineovenstatus.setText)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineovenstatus.setFont(font)
        self.lineovenstatus.setFrame(False)
        self.lineovenstatus.setReadOnly(True)
        self.lineovenstatus.setObjectName("lineovenstatus")
        self.verticalLayout_10.addWidget(self.lineovenstatus)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_3.addWidget(self.statusframe)
        self.TempFrame = QtGui.QFrame(self.layoutWidget)
        self.TempFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.TempFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.TempFrame.setLineWidth(0)
        self.TempFrame.setObjectName("TempFrame")
        self.gridLayout = QtGui.QGridLayout(self.TempFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.cjtemp = QtGui.QLCDNumber(self.TempFrame)
        self.cjtemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.cjtemp.setObjectName("cjtemp")
        self.gridLayout.addWidget(self.cjtemp, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.TempFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.TempFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.probetemp = QtGui.QLCDNumber(self.TempFrame)
        self.probetemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.probetemp.setObjectName("probetemp")
        comm.newTemp.connect(self.probetemp.display)
        self.gridLayout.addWidget(self.probetemp, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.TempFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.TempFrame)
        self.ProfileFrame = QtGui.QFrame(self.layoutWidget)
        self.ProfileFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.ProfileFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.ProfileFrame.setLineWidth(0)
        self.ProfileFrame.setObjectName("ProfileFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.ProfileFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lblprogram = QtGui.QLabel(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblprogram.setFont(font)
        self.lblprogram.setObjectName("lblprogram")
        self.verticalLayout.addWidget(self.lblprogram)
        self.lineprogram = QtGui.QLineEdit(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineprogram.setFont(font)
        self.lineprogram.setMaxLength(32767)
        self.lineprogram.setReadOnly(True)
        self.lineprogram.setObjectName("lineprogram")
        self.verticalLayout.addWidget(self.lineprogram)
        self.lbltagettemp = QtGui.QLabel(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbltagettemp.setFont(font)
        self.lbltagettemp.setObjectName("lbltagettemp")
        self.verticalLayout.addWidget(self.lbltagettemp)
        self.linetargettemp = QtGui.QLineEdit(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linetargettemp.setFont(font)
        self.linetargettemp.setReadOnly(True)
        self.linetargettemp.setObjectName("linetargettemp")
        self.verticalLayout.addWidget(self.linetargettemp)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbltset = QtGui.QLabel(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbltset.setFont(font)
        self.lbltset.setObjectName("lbltset")
        self.verticalLayout_8.addWidget(self.lbltset)
        self.linetset = QtGui.QLineEdit(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linetset.setFont(font)
        self.linetset.setCursorPosition(0)
        self.linetset.setAlignment(QtCore.Qt.AlignCenter)
        self.linetset.setReadOnly(True)
        self.linetset.setObjectName("linetset")
        self.verticalLayout_8.addWidget(self.linetset)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbltimeleft = QtGui.QLabel(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbltimeleft.setFont(font)
        self.lbltimeleft.setObjectName("lbltimeleft")
        self.verticalLayout_9.addWidget(self.lbltimeleft)
        self.linetleft = QtGui.QLineEdit(self.ProfileFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linetleft.setFont(font)
        self.linetleft.setAlignment(QtCore.Qt.AlignCenter)
        self.linetleft.setReadOnly(True)
        self.linetleft.setObjectName("linetleft")
        self.verticalLayout_9.addWidget(self.linetleft)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.ProfileFrame)
        self.HeaterFrame = QtGui.QFrame(self.layoutWidget)
        self.HeaterFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.HeaterFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.HeaterFrame.setLineWidth(0)
        self.HeaterFrame.setObjectName("HeaterFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.HeaterFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblheaterusage = QtGui.QLabel(self.HeaterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblheaterusage.setFont(font)
        self.lblheaterusage.setObjectName("lblheaterusage")
        self.verticalLayout_2.addWidget(self.lblheaterusage)
        self.prgheaterbar = QtGui.QProgressBar(self.HeaterFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prgheaterbar.setFont(font)
        self.prgheaterbar.setProperty("value", QtCore.QVariant(0))
        self.prgheaterbar.setInvertedAppearance(False)
        self.prgheaterbar.setObjectName("prgheaterbar")
        self.verticalLayout_2.addWidget(self.prgheaterbar)
        self.verticalLayout_3.addWidget(self.HeaterFrame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_3 = QtGui.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(21, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btnabout = QtGui.QPushButton(self.frame_3)
        self.btnabout.setMaximumSize(QtCore.QSize(99, 16777215))
        self.btnabout.setObjectName("btnabout")
        self.verticalLayout_14.addWidget(self.btnabout)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chartframe = QtGui.QFrame(self.layoutWidget)
        self.chartframe.setMinimumSize(QtCore.QSize(600, 500))
        self.chartframe.setFrameShape(QtGui.QFrame.WinPanel)
        self.chartframe.setFrameShadow(QtGui.QFrame.Plain)
        self.chartframe.setLineWidth(0)
        self.chartframe.setObjectName("chartframe")
        self.verticalLayout_4.addWidget(self.chartframe)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtplotframe = QtGui.QFrame(self.layoutWidget)
        self.txtplotframe.setFrameShape(QtGui.QFrame.WinPanel)
        self.txtplotframe.setFrameShadow(QtGui.QFrame.Plain)
        self.txtplotframe.setLineWidth(0)
        self.txtplotframe.setObjectName("txtplotframe")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.txtplotframe)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblred = QtGui.QLabel(self.txtplotframe)
        self.lblred.setMaximumSize(QtCore.QSize(20, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblred.setFont(font)
        self.lblred.setObjectName("lblred")
        self.horizontalLayout_8.addWidget(self.lblred)
        self.label_5 = QtGui.QLabel(self.txtplotframe)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblblue = QtGui.QLabel(self.txtplotframe)
        self.lblblue.setMaximumSize(QtCore.QSize(20, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblblue.setFont(font)
        self.lblblue.setObjectName("lblblue")
        self.horizontalLayout_9.addWidget(self.lblblue)
        self.label_6 = QtGui.QLabel(self.txtplotframe)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblgreen = QtGui.QLabel(self.txtplotframe)
        self.lblgreen.setMaximumSize(QtCore.QSize(20, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblgreen.setFont(font)
        self.lblgreen.setObjectName("lblgreen")
        self.horizontalLayout_10.addWidget(self.lblgreen)
        self.label_7 = QtGui.QLabel(self.txtplotframe)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.btnclear = QtGui.QPushButton(self.txtplotframe)
        self.btnclear.setObjectName("btnclear")
        self.verticalLayout_7.addWidget(self.btnclear)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addWidget(self.txtplotframe)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 70))
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbllog = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbllog.setFont(font)
        self.lbllog.setObjectName("lbllog")
        self.horizontalLayout_6.addWidget(self.lbllog)
        self.recled = QtGui.QLabel(self.frame)
        self.recled.setEnabled(True)
        self.recled.setMinimumSize(QtCore.QSize(8, 8))
        self.recled.setMaximumSize(QtCore.QSize(16, 16))
        self.recled.setSizeIncrement(QtCore.QSize(0, 0))
        self.recled.setPixmap(QtGui.QPixmap("images/rec_off.png"))
        self.recled.setScaledContents(False)
        self.recled.setObjectName("recled")
        self.horizontalLayout_6.addWidget(self.recled)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linefile = QtGui.QLineEdit(self.frame)
        self.linefile.setObjectName("linefile")
        self.horizontalLayout.addWidget(self.linefile)
        self.toolButton = QtGui.QToolButton(self.frame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chkauto = QtGui.QCheckBox(self.frame)
        self.chkauto.setObjectName("chkauto")
        self.horizontalLayout_5.addWidget(self.chkauto)
        self.btnrec = QtGui.QPushButton(self.frame)
        self.btnrec.setObjectName("btnrec")
        self.horizontalLayout_5.addWidget(self.btnrec)
        self.btnstop = QtGui.QPushButton(self.frame)
        self.btnstop.setObjectName("btnstop")
        self.horizontalLayout_5.addWidget(self.btnstop)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_12.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        spacerItem2 = QtGui.QSpacerItem(138, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.frame_2 = QtGui.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btnconnect = QtGui.QPushButton(self.frame_2)
        self.btnconnect.setObjectName("btnconnect")
        self.verticalLayout_13.addWidget(self.btnconnect)
        spacerItem3 = QtGui.QSpacerItem(72, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.btnExit = QtGui.QPushButton(self.frame_2)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout_13.addWidget(self.btnExit)
        self.verticalLayout_6.addLayout(self.verticalLayout_13)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnExit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.linefile, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.chkauto)
        MainWindow.setTabOrder(self.chkauto, self.btnrec)
        MainWindow.setTabOrder(self.btnrec, self.btnstop)
        MainWindow.setTabOrder(self.btnstop, self.linetargettemp)
        MainWindow.setTabOrder(self.linetargettemp, self.linetset)
        MainWindow.setTabOrder(self.linetset, self.lineovenstatus)
        MainWindow.setTabOrder(self.lineovenstatus, self.linetleft)
        MainWindow.setTabOrder(self.linetleft, self.lineprogram)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", " Reflow Oven", None, QtGui.QApplication.UnicodeUTF8))
        self.lblovenstatus.setText(QtGui.QApplication.translate("MainWindow", "Oven Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "CJ Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Oven Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Temperature ºC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Active Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.lblprogram.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltagettemp.setText(QtGui.QApplication.translate("MainWindow", "Target Temp ºC", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltset.setText(QtGui.QApplication.translate("MainWindow", "Time Set", None, QtGui.QApplication.UnicodeUTF8))
        self.linetset.setInputMask(QtGui.QApplication.translate("MainWindow", "00:00; ", None, QtGui.QApplication.UnicodeUTF8))
        self.linetset.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltimeleft.setText(QtGui.QApplication.translate("MainWindow", "Time Left", None, QtGui.QApplication.UnicodeUTF8))
        self.linetleft.setInputMask(QtGui.QApplication.translate("MainWindow", "00:00; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblheaterusage.setText(QtGui.QApplication.translate("MainWindow", "Heater Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.btnabout.setText(QtGui.QApplication.translate("MainWindow", "A&bout ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblred.setText(QtGui.QApplication.translate("MainWindow", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Oven Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.lblblue.setText(QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Target Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.lblgreen.setText(QtGui.QApplication.translate("MainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "CJ Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.btnclear.setText(QtGui.QApplication.translate("MainWindow", "C&lear", None, QtGui.QApplication.UnicodeUTF8))
        self.lbllog.setText(QtGui.QApplication.translate("MainWindow", "Log Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.chkauto.setText(QtGui.QApplication.translate("MainWindow", "&Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.btnrec.setText(QtGui.QApplication.translate("MainWindow", "&Rec", None, QtGui.QApplication.UnicodeUTF8))
        self.btnstop.setText(QtGui.QApplication.translate("MainWindow", "&Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btnconnect.setText(QtGui.QApplication.translate("MainWindow", "&Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))

